/**
 * STARDESK kodepraksis-50 — plan, verify steps, and fallback ladder per item.
 * Source: workboard/constitution/STARDESK-kodepraksis-50.md
 */

/** @typedef {'open'|'in_progress'|'done'|'partial'|'deferred'|'wontfix'} ItemStatus */
/** @typedef {'full'|'partial'|'defer'|'skip'} FallbackLevel */

/**
 * @typedef {object} FallbackStep
 * @property {FallbackLevel} level
 * @property {string} scope
 * @property {string} when
 */

/**
 * @typedef {object} PlanItem
 * @property {number} n
 * @property {string} title
 * @property {string} category
 * @property {number} execOrder
 * @property {string} relevance
 * @property {boolean} incremental
 * @property {string} primaryScope
 * @property {string[]} verify
 * @property {FallbackStep[]} fallback
 * @property {number[]} blockedBy
 * @property {string} debateNote
 */

/** Execution order: week plan + dependencies (lint/hooks before big refactors). */
export const EXEC_ORDER = [
  39, 40, 43, 44, 50, 3, 41, 42, 1, 2, 7, 8, 10, 4, 9, 5, 6, 11, 12, 18, 13, 14, 17, 19, 20,
  21, 29, 22, 23, 24, 25, 30, 26, 27, 28, 15, 16, 31, 32, 33, 34, 35, 36, 37, 38, 45, 46, 47, 48,
  49,
];

/** @type {PlanItem[]} */
export const PLAN_ITEMS = [
  {
    n: 1,
    title: "Router return type annotations (144 endpoints)",
    category: "TYPING",
    execOrder: 9,
    relevance: "high — closes largest typing gap vs services",
    incremental: true,
    primaryScope: "Add return types + AsyncSession on all router handlers; start tickets.py + auth.py",
    verify: ["cd apps/api && uv run ruff check routers/", "cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "Top 20 highest-traffic endpoints only", when: "Full pass breaks OpenAPI or >2h churn" },
      { level: "defer", scope: "Leave remaining routers typed incrementally per PR", when: "CI red after 2 fix attempts" },
      { level: "skip", scope: "Mark wontfix for prototype-only routers", when: "Endpoint marked deprecated in code" },
    ],
    blockedBy: [],
    debateNote: "High value; pair with #2 incrementally per router file.",
  },
  {
    n: 2,
    title: "Pydantic response_model on all endpoints",
    category: "TYPING",
    execOrder: 10,
    relevance: "high — OpenAPI + runtime response validation",
    incremental: true,
    primaryScope: "Add response_model to every router decorator; one router file per PR",
    verify: ["cd apps/api && uv run pytest -q tests/", "curl -s localhost:8000/openapi.json | head"],
    fallback: [
      { level: "partial", scope: "Staff-facing routers first (tickets, kanban, reports)", when: "Schema mismatch on legacy dict returns" },
      { level: "defer", scope: "Document endpoints returning raw dict until #8", when: "Requires service return type refactor first" },
      { level: "skip", scope: "Webhooks/streaming endpoints without JSON body", when: "Non-JSON response by design" },
    ],
    blockedBy: [8],
    debateNote: "Depends on stable Pydantic read models; do file-by-file with #1.",
  },
  {
    n: 3,
    title: "Ruff ANN, TCH, PYI typing rules",
    category: "TYPING",
    execOrder: 6,
    relevance: "medium — enforces annotations after #1",
    incremental: true,
    primaryScope: "Extend pyproject select with ANN,TCH,PYI; fix per package",
    verify: ["cd apps/api && uv run ruff check ."],
    fallback: [
      { level: "partial", scope: "ANN on routers/ only", when: ">200 new violations repo-wide" },
      { level: "defer", scope: "Enable PYI only after ANN clean", when: "Stub churn blocks sprint" },
      { level: "skip", scope: "Exclude generated migrations folder", when: "Alembic autogen" },
    ],
    blockedBy: [39],
    debateNote: "Run after base Ruff expansion (#39) to avoid double noise.",
  },
  {
    n: 4,
    title: "py.typed marker package",
    category: "TYPING",
    execOrder: 14,
    relevance: "low for internal monorepo; high if API published",
    incremental: true,
    primaryScope: "Add star_itsm_api/py.typed empty marker",
    verify: ["test -f apps/api/src/star_itsm_api/py.typed"],
    fallback: [
      { level: "partial", scope: "Marker only, no strict downstream yet", when: "N/A" },
      { level: "defer", scope: "Wait until #6 codegen", when: "No external Python consumers" },
      { level: "skip", scope: "Skip until public package", when: "Product decision" },
    ],
    blockedBy: [],
    debateNote: "Cheap win; do when touching packaging.",
  },
  {
    n: 5,
    title: "Frontend Zod validation for API responses",
    category: "TYPING",
    execOrder: 15,
    relevance: "high for portal/staff UX safety",
    incremental: true,
    primaryScope: "Zod parse in api.ts for tickets, auth, kanban first",
    verify: ["cd apps/web && npm run lint", "cd apps/web && npm run build"],
    fallback: [
      { level: "partial", scope: "Critical paths: login + ticket detail only", when: "Schema drift from API" },
      { level: "defer", scope: "Loose z.unknown() bridge per endpoint", when: "OpenAPI codegen scheduled (#6)" },
      { level: "skip", scope: "Static marketing pages", when: "No API fetch" },
    ],
    blockedBy: [],
    debateNote: "Pragmatic before shared codegen.",
  },
  {
    n: 6,
    title: "Shared API types (OpenAPI codegen or package)",
    category: "TYPING",
    execOrder: 16,
    relevance: "medium — reduces duplicate TS types",
    incremental: true,
    primaryScope: "Script: openapi-typescript from /openapi.json → apps/web/src/types/api.gen.ts",
    verify: ["cd apps/web && npm run build"],
    fallback: [
      { level: "partial", scope: "Codegen tickets + auth namespaces only", when: "Huge diff" },
      { level: "defer", scope: "Manual types + Zod (#5) until OpenAPI complete (#2)", when: "Missing response_model" },
      { level: "skip", scope: "Stay manual types", when: "Team rejects codegen churn" },
    ],
    blockedBy: [2, 46],
    debateNote: "Best after response_model coverage.",
  },
  {
    n: 7,
    title: "Annotated Depends aliases (CurrentUser, DbSession, …)",
    category: "TYPING",
    execOrder: 11,
    relevance: "high — DRY for Depends patterns",
    incremental: true,
    primaryScope: "deps.py aliases; migrate tickets.py + top routers",
    verify: ["cd apps/api && uv run ruff check .", "cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "Staff deps only (require_staff, CurrentUser)", when: "Large diff" },
      { level: "defer", scope: "New code only rule in CONTRIBUTING", when: "Migration too noisy" },
      { level: "skip", scope: "N/A", when: "Already done" },
    ],
    blockedBy: [11],
    debateNote: "Synergy with permission dependencies #11.",
  },
  {
    n: 8,
    title: "Replace dict/list returns in services with Pydantic/TypedDict",
    category: "TYPING",
    execOrder: 13,
    relevance: "medium — unlocks #2",
    incremental: true,
    primaryScope: "Grep services returning dict; fix top 10 call sites",
    verify: ["cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "Ticket + dashboard services only", when: "Wide dict usage" },
      { level: "defer", scope: "TypedDict interim for nested dynamic keys", when: "Schema unstable" },
      { level: "skip", scope: "Admin export raw CSV dict", when: "Intentionally unstructured" },
    ],
    blockedBy: [],
    debateNote: "Do before full response_model rollout.",
  },
  {
    n: 9,
    title: "Verify generics on optional_db_read for pyright",
    category: "TYPING",
    execOrder: 14,
    relevance: "low — already PEP 695",
    incremental: true,
    primaryScope: "Add pyrightconfig; fix db_resilience typing errors only",
    verify: ["cd apps/api && uv run pyright src/star_itsm_api/db_resilience.py 2>/dev/null || true"],
    fallback: [
      { level: "partial", scope: "Document typing in docstring only", when: "pyright not in CI" },
      { level: "defer", scope: "Bundle with #10", when: "No pyright in dev deps" },
      { level: "skip", scope: "mypy alternative", when: "Team picks mypy" },
    ],
    blockedBy: [10],
    debateNote: "Small; pair with strict baseline #10.",
  },
  {
    n: 10,
    title: "pyright/mypy strict baseline (worst 50)",
    category: "TYPING",
    execOrder: 12,
    relevance: "medium — long-term",
    incremental: true,
    primaryScope: "Add pyright to dev group; baseline file; fix 50 errors",
    verify: ["cd apps/api && uv run pyright --warnings"],
    fallback: [
      { level: "partial", scope: "strict on services/ only", when: "Routers explode errors" },
      { level: "defer", scope: "reportUnusedImport=false baseline", when: "Blocks sprint" },
      { level: "skip", scope: "Ruff ANN only (#3)", when: "No bandwidth for second checker" },
    ],
    blockedBy: [1, 3],
    debateNote: "After router annotations and Ruff ANN.",
  },
  {
    n: 11,
    title: "Extract 72 permission checks to require_staff deps",
    category: "DRY",
    execOrder: 18,
    relevance: "critical — highest DRY win",
    incremental: true,
    primaryScope: "require_staff + require_agent in deps; codemod routers",
    verify: ["cd apps/api && uv run pytest -q tests/test_permissions.py", "cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "tickets.py + kanban.py only (bulk of checks)", when: "Codemod breaks tests" },
      { level: "defer", scope: "New endpoints must use Depends; legacy untouched", when: "PR too large" },
      { level: "skip", scope: "Keep inline check where custom message needed", when: "Non-standard authz" },
    ],
    blockedBy: [],
    debateNote: "Week 2 priority; minimal behavior change.",
  },
  {
    n: 12,
    title: "ticket_repository.py central get_ticket",
    category: "DRY",
    execOrder: 19,
    relevance: "critical — 14 duplicate fetches",
    incremental: true,
    primaryScope: "repositories/ticket_repository.py + replace duplicates",
    verify: ["cd apps/api && uv run pytest -q tests/"],
    fallback: [
      { level: "partial", scope: "Replace 5 duplicates in tickets.py first", when: "Org-scope variants differ" },
      { level: "defer", scope: "Helper get_ticket_or_404 only", when: "Soft-delete edge cases" },
      { level: "skip", scope: "Keep specialized joins inline", when: "Performance needs custom selectinload" },
    ],
    blockedBy: [],
    debateNote: "Aligns with performance plan #5.",
  },
  {
    n: 13,
    title: "Shared query builders: pagination, sort, org scope",
    category: "DRY",
    execOrder: 21,
    relevance: "medium",
    incremental: true,
    primaryScope: "query_helpers.py; migrate list_tickets + list_users",
    verify: ["cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "apply_pagination only", when: "Org scope logic diverges" },
      { level: "defer", scope: "Document pattern; adopt on touch", when: "Risky merge" },
      { level: "skip", scope: "N/A", when: "Exists" },
    ],
    blockedBy: [12],
    debateNote: "After ticket repository exists.",
  },
  {
    n: 14,
    title: "Shared Pydantic base schemas (timestamps, audit, pagination)",
    category: "DRY",
    execOrder: 22,
    relevance: "medium",
    incremental: true,
    primaryScope: "schemas/base.py with TimestampedMixin, Page[T]",
    verify: ["cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "Pagination response only", when: "Breaking API shape" },
      { level: "defer", scope: "New schemas inherit; old unchanged", when: "Migration cost" },
      { level: "skip", scope: "N/A", when: "Done" },
    ],
    blockedBy: [],
    debateNote: "Non-breaking if additive fields only.",
  },
  {
    n: 15,
    title: "Frontend hooks: useTicketForm, useTicketList, useKanbanBoard",
    category: "DRY",
    execOrder: 40,
    relevance: "medium",
    incremental: true,
    primaryScope: "Extract from create-ticket-form + kanban-board-view",
    verify: ["cd apps/web && npm run lint", "bash scripts/run-deliverable-gate.sh --full"],
    fallback: [
      { level: "partial", scope: "useTicketForm only", when: "Kanban drag too coupled" },
      { level: "defer", scope: "Hook extraction on next UI PR", when: "No test coverage (#31)" },
      { level: "skip", scope: "N/A", when: "Components <400 lines after #26-27" },
    ],
    blockedBy: [31],
    debateNote: "After first component tests.",
  },
  {
    n: 16,
    title: "Frontend api/* modules per domain",
    category: "DRY",
    execOrder: 41,
    relevance: "medium",
    incremental: true,
    primaryScope: "api/tickets.ts, api/kanban.ts; move inline fetch",
    verify: ["cd apps/web && npm run build"],
    fallback: [
      { level: "partial", scope: "tickets.ts only", when: "Timeboxed" },
      { level: "defer", scope: "Enforce in eslint no-restricted-imports later", when: "Large diff" },
      { level: "skip", scope: "Server Components fetch stays colocated", when: "RSC pattern" },
    ],
    blockedBy: [],
    debateNote: "Client components first.",
  },
  {
    n: 17,
    title: "Versioned idempotent seeds/ module",
    category: "DRY",
    execOrder: 23,
    relevance: "low-medium",
    incremental: true,
    primaryScope: "seeds/ with manifest; wire bootstrap script",
    verify: ["bash scripts/bootstrap-dev-database.sh"],
    fallback: [
      { level: "partial", scope: "Document seed order only", when: "Bootstrap fragile" },
      { level: "defer", scope: "Keep init.sql; add README", when: "Neon branch reset rare" },
      { level: "skip", scope: "N/A", when: "init.sql sufficient" },
    ],
    blockedBy: [],
    debateNote: "Ops hygiene; not user-facing.",
  },
  {
    n: 18,
    title: "HTTP error helpers: not_found, forbidden, bad_request",
    category: "DRY",
    execOrder: 20,
    relevance: "high — pairs #49",
    incremental: true,
    primaryScope: "errors.py helpers; replace HTTPException literals in 3 routers",
    verify: ["cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "forbidden + not_found only", when: "RFC7807 migration pending" },
      { level: "defer", scope: "New code uses helpers", when: "Large string detail churn" },
      { level: "skip", scope: "N/A", when: "Exists" },
    ],
    blockedBy: [],
    debateNote: "Week 2; foundation for #49.",
  },
  {
    n: 19,
    title: "Unified mail/notification service module",
    category: "DRY",
    execOrder: 24,
    relevance: "medium",
    incremental: true,
    primaryScope: "Consolidate mail send paths into notifications/service",
    verify: ["cd apps/api && uv run pytest -q tests/test_mail.py"],
    fallback: [
      { level: "partial", scope: "Resend path only", when: "Gmail mock paths differ" },
      { level: "defer", scope: "Interface only; move one caller", when: "Risky prod mail" },
      { level: "skip", scope: "N/A", when: "Already centralized" },
    ],
    blockedBy: [],
    debateNote: "Careful with Resend prod.",
  },
  {
    n: 20,
    title: "Shared DataTable component for list views",
    category: "DRY",
    execOrder: 42,
    relevance: "medium UI",
    incremental: true,
    primaryScope: "components/data-table.tsx; migrate tickets list first",
    verify: ["bash scripts/run-deliverable-gate.sh --full"],
    fallback: [
      { level: "partial", scope: "Column defs only shared hook", when: "Table APIs differ too much" },
      { level: "defer", scope: "shadcn Table wrapper without full abstraction", when: "Design review needed" },
      { level: "skip", scope: "Kanban excluded", when: "Not tabular" },
    ],
    blockedBy: [31],
    debateNote: "After list view tests.",
  },
  {
    n: 21,
    title: "Split tickets.py into 6 domain routers",
    category: "SRP",
    execOrder: 25,
    relevance: "critical",
    incremental: true,
    primaryScope: "routers/tickets/{crud,comments,attachments,sla,import,admin}.py + include_router",
    verify: ["cd apps/api && uv run pytest -q", "bash scripts/run-deliverable-gate.sh"],
    fallback: [
      { level: "partial", scope: "Extract comments + attachments first (2 files)", when: "1651-line PR blocked" },
      { level: "defer", scope: "Stop at 3 files; continue next sprint", when: "Merge conflicts" },
      { level: "skip", scope: "N/A", when: "Already split" },
    ],
    blockedBy: [11, 12],
    debateNote: "Week 3; must be incremental PRs.",
  },
  {
    n: 22,
    title: "Split import_tickets_admin (203 lines)",
    category: "SRP",
    execOrder: 26,
    relevance: "medium",
    incremental: true,
    primaryScope: "parse → validate → insert → post_process functions",
    verify: ["cd apps/api && uv run pytest -q tests/test_import"],
    fallback: [
      { level: "partial", scope: "Extract validate+insert only", when: "Timeboxed" },
      { level: "defer", scope: "Add noqa C901 until split", when: "Blocked by import bugs" },
      { level: "skip", scope: "N/A", when: "Under 50 lines" },
    ],
    blockedBy: [21],
    debateNote: "Can ship before full tickets.py split.",
  },
  {
    n: 23,
    title: "Split list_tickets (186 lines)",
    category: "SRP",
    execOrder: 27,
    relevance: "medium",
    incremental: true,
    primaryScope: "parse_filters, build_query, execute, serialize",
    verify: ["cd apps/api && uv run pytest -q tests/test_tickets"],
    fallback: [
      { level: "partial", scope: "extract build_query only", when: "Filter bugs risk" },
      { level: "defer", scope: "Pair with #13 query helpers", when: "Duplicate abstraction" },
      { level: "skip", scope: "N/A", when: "Done" },
    ],
    blockedBy: [12, 13],
    debateNote: "High traffic path — extra tests.",
  },
  {
    n: 24,
    title: "Split build_dashboard (181 lines)",
    category: "SRP",
    execOrder: 28,
    relevance: "medium",
    incremental: true,
    primaryScope: "Widget functions per metric group",
    verify: ["cd apps/api && uv run pytest -q tests/test_reports"],
    fallback: [
      { level: "partial", scope: "One widget extracted as pattern", when: "Dashboard regressions" },
      { level: "defer", scope: "Cache layer first (performance #31)", when: "Perf emergency" },
      { level: "skip", scope: "N/A", when: "Under 50 lines" },
    ],
    blockedBy: [],
    debateNote: "Independent of tickets split.",
  },
  {
    n: 25,
    title: "Split sync_gmail_inbox (143 lines)",
    category: "SRP",
    execOrder: 29,
    relevance: "medium",
    incremental: true,
    primaryScope: "fetch → parse → create_ticket → update_state",
    verify: ["cd apps/api && uv run pytest -q tests/test_gmail"],
    fallback: [
      { level: "partial", scope: "Extract fetch+parse only", when: "GMAIL_MOCK=1 tests fail" },
      { level: "defer", scope: "Document stages in comments", when: "No gmail tests" },
      { level: "skip", scope: "N/A", when: "Mock-only path stable" },
    ],
    blockedBy: [],
    debateNote: "Keep mock path green.",
  },
  {
    n: 26,
    title: "Split create-ticket-form.tsx (787 lines)",
    category: "SRP",
    execOrder: 39,
    relevance: "high UI",
    incremental: true,
    primaryScope: "form hook + field components + submit module",
    verify: ["bash scripts/run-deliverable-gate.sh --full"],
    fallback: [
      { level: "partial", scope: "Extract TicketFormFields.tsx only", when: "Regression in portal" },
      { level: "defer", scope: "Split after #31 tests", when: "No safety net" },
      { level: "skip", scope: "N/A", when: "<400 lines" },
    ],
    blockedBy: [31],
    debateNote: "Portal-critical; tests first.",
  },
  {
    n: 27,
    title: "Split kanban-board-view.tsx (657 lines)",
    category: "SRP",
    execOrder: 40,
    relevance: "high UI",
    incremental: true,
    primaryScope: "board / column / card / dnd handlers",
    verify: ["bash scripts/run-deliverable-gate.sh --full"],
    fallback: [
      { level: "partial", scope: "Extract KanbanCard only", when: "DnD breaks" },
      { level: "defer", scope: "Stop at 2 files", when: "Playwright flaky" },
      { level: "skip", scope: "N/A", when: "Done" },
    ],
    blockedBy: [31],
    debateNote: "Drag-drop is fragile.",
  },
  {
    n: 28,
    title: "Split sf-chat-agent-console.tsx (495 lines)",
    category: "SRP",
    execOrder: 41,
    relevance: "medium",
    incremental: true,
    primaryScope: "chat-window, message-list, input, actions",
    verify: ["cd apps/web && npm run lint"],
    fallback: [
      { level: "partial", scope: "Extract message-list only", when: "Timeboxed" },
      { level: "defer", scope: "Next SF sprint", when: "Low traffic feature" },
      { level: "skip", scope: "N/A", when: "Under 400 lines" },
    ],
    blockedBy: [],
    debateNote: "Lower priority than tickets/kanban.",
  },
  {
    n: 29,
    title: "Enforce max 50 lines / 400 lines per file (Ruff C901, PLR0915)",
    category: "SRP",
    execOrder: 26,
    relevance: "medium — policy",
    incremental: true,
    primaryScope: "Add per-file ignores for legacy; ratchet new code",
    verify: ["cd apps/api && uv run ruff check ."],
    fallback: [
      { level: "partial", scope: "Warn-only in CI comment", when: "500+ violations day one" },
      { level: "defer", scope: "max-complexity=15 only, not line count", when: "Team rejects PLR0915" },
      { level: "skip", scope: "Document in CONTRIBUTING only", when: "No enforcement appetite" },
    ],
    blockedBy: [39],
    debateNote: "Ratchet after splits #21-28.",
  },
  {
    n: 30,
    title: "Move 22 inline text() SQL to queries/ or ORM",
    category: "SRP",
    execOrder: 30,
    relevance: "medium",
    incremental: true,
    primaryScope: "Audit text(); convert 5 per PR to SQLAlchemy",
    verify: ["cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "Document allowed raw SQL cases", when: "Report queries need raw" },
      { level: "defer", scope: "sqlglot review later", when: "Risky reports" },
      { level: "skip", scope: "Keep text() in analytics", when: "Complex SQL" },
    ],
    blockedBy: [],
    debateNote: "Security review for string concat.",
  },
  {
    n: 31,
    title: "Frontend test suite start (3 critical components)",
    category: "TEST",
    execOrder: 36,
    relevance: "critical",
    incremental: true,
    primaryScope: "Vitest + RTL for create-ticket-form, kanban, service-desk-view",
    verify: ["cd apps/web && npm run test", "bash scripts/run-deliverable-gate.sh --full"],
    fallback: [
      { level: "partial", scope: "One component smoke test", when: "Vitest not configured" },
      { level: "defer", scope: "Playwright-only coverage (#36)", when: "RTL setup blocked" },
      { level: "skip", scope: "N/A", when: "Tests exist" },
    ],
    blockedBy: [40],
    debateNote: "Week 4; unlocks #15-20, #26-27.",
  },
  {
    n: 32,
    title: "API integration tests (API→DB→response)",
    category: "TEST",
    execOrder: 37,
    relevance: "high",
    incremental: true,
    primaryScope: "tests/integration/ with httpx ASGI + Neon test DB",
    verify: ["cd apps/api && uv run pytest -q tests/integration"],
    fallback: [
      { level: "partial", scope: "auth + tickets happy path only", when: "DB flake" },
      { level: "defer", scope: "Extend existing e2e gate", when: "No DATABASE_URL" },
      { level: "skip", scope: "N/A", when: "Covered by deliverable gate" },
    ],
    blockedBy: [],
    debateNote: "Use Neon test branch only.",
  },
  {
    n: 33,
    title: "Contract tests: responses match Pydantic schemas",
    category: "TEST",
    execOrder: 38,
    relevance: "medium",
    incremental: true,
    primaryScope: "schemathesis or custom assert response validates model",
    verify: ["cd apps/api && uv run pytest -q tests/contract"],
    fallback: [
      { level: "partial", scope: "5 critical endpoints", when: "OpenAPI incomplete (#2)" },
      { level: "defer", scope: "After #2 response_model", when: "Schema drift" },
      { level: "skip", scope: "N/A", when: "Manual OpenAPI review enough" },
    ],
    blockedBy: [2],
    debateNote: "Depends on response_model.",
  },
  {
    n: 34,
    title: "Shared test fixtures (ticket, user, team, org)",
    category: "TEST",
    execOrder: 39,
    relevance: "medium",
    incremental: true,
    primaryScope: "conftest factories; dedupe setup",
    verify: ["cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "ticket + user factories only", when: "Timeboxed" },
      { level: "defer", scope: "On touch migration", when: "Huge conftest diff" },
      { level: "skip", scope: "N/A", when: "Exists" },
    ],
    blockedBy: [],
    debateNote: "Do early with #32.",
  },
  {
    n: 35,
    title: "Snapshot tests for ticket-detail API",
    category: "TEST",
    execOrder: 43,
    relevance: "low-medium",
    incremental: true,
    primaryScope: "pytest-snapshot on ticket detail JSON (redact ids)",
    verify: ["cd apps/api && uv run pytest -q tests/snapshots"],
    fallback: [
      { level: "partial", scope: "Inline assert key fields only", when: "Snapshot churn" },
      { level: "defer", scope: "After schema stable (#2)", when: "Frequent breaks" },
      { level: "skip", scope: "N/A", when: "Rejected by team" },
    ],
    blockedBy: [2],
    debateNote: "Sensitive to seed data.",
  },
  {
    n: 36,
    title: "Expand e2e to 5 critical user flows",
    category: "TEST",
    execOrder: 44,
    relevance: "high",
    incremental: true,
    primaryScope: "Playwright: login, list, create ticket, kanban move, portal",
    verify: ["bash scripts/run-deliverable-gate.sh --full"],
    fallback: [
      { level: "partial", scope: "Add 2 flows this sprint", when: "Flaky staging" },
      { level: "defer", scope: "Deliverable gate flows only", when: "CI time budget" },
      { level: "skip", scope: "N/A", when: "5 flows exist" },
    ],
    blockedBy: [],
    debateNote: "Extends hello-world gate.",
  },
  {
    n: 37,
    title: "Performance regression tests on list endpoints",
    category: "TEST",
    execOrder: 45,
    relevance: "medium",
    incremental: true,
    primaryScope: "pytest mark perf; assert p95 < 2s on tickets list",
    verify: ["cd apps/api && uv run pytest -q -m perf"],
    fallback: [
      { level: "partial", scope: "Document threshold; manual perf agent", when: "CI variable latency" },
      { level: "defer", scope: "Use scripts/performance-agent only", when: "Neon cold start noise" },
      { level: "skip", scope: "N/A", when: "k6 covers it" },
    ],
    blockedBy: [],
    debateNote: "Align thresholds with performance-50 #50.",
  },
  {
    n: 38,
    title: "Permission boundary tests (end_user vs agent)",
    category: "TEST",
    execOrder: 38,
    relevance: "critical security-adjacent",
    incremental: true,
    primaryScope: "Parametrize role × endpoint matrix for 403",
    verify: ["cd apps/api && uv run pytest -q tests/test_permissions.py"],
    fallback: [
      { level: "partial", scope: "Top 10 agent endpoints", when: "Matrix too large" },
      { level: "defer", scope: "After #11 require_staff", when: "Duplicate setup" },
      { level: "skip", scope: "N/A", when: "Covered" },
    ],
    blockedBy: [11],
    debateNote: "Week 4; do with or after #11.",
  },
  {
    n: 39,
    title: "Expand Ruff: C90, D, S, SIM, PTH, RET, ARG",
    category: "LINT",
    execOrder: 1,
    relevance: "critical quick win",
    incremental: true,
    primaryScope: "pyproject.toml select += C90,D,S,SIM,PTH,RET,ARG; fix violations in batches",
    verify: ["cd apps/api && uv run ruff check .", "cd apps/api && uv run pytest -q"],
    fallback: [
      { level: "partial", scope: "Enable SIM+RET+ARG only (no D/S first)", when: ">100 D/S violations" },
      { level: "defer", scope: "per-file-ignores for tickets.py until #21 split", when: "C901 blocks merge" },
      { level: "skip", scope: "Keep E,F,I,UP only", when: "Team rejects docstring police (D)" },
    ],
    blockedBy: [],
    debateNote: "Week 1 item 1 — start here.",
  },
  {
    n: 40,
    title: "pre-commit: ruff, eslint, tsc --noEmit",
    category: "LINT",
    execOrder: 2,
    relevance: "critical",
    incremental: true,
    primaryScope: ".pre-commit-config.yaml + docs in CONTRIBUTING",
    verify: ["pre-commit run --all-files"],
    fallback: [
      { level: "partial", scope: "ruff only hook; CI runs eslint", when: "Windows hook friction" },
      { level: "defer", scope: "CI-only enforcement (#41)", when: "Devs skip hooks" },
      { level: "skip", scope: "N/A", when: "Already configured" },
    ],
    blockedBy: [39],
    debateNote: "After Ruff rules stable.",
  },
  {
    n: 41,
    title: "CI lint+test on all PRs",
    category: "LINT",
    execOrder: 7,
    relevance: "high — likely exists; verify gap",
    incremental: true,
    primaryScope: "Audit .github/workflows; add missing ruff/eslint job",
    verify: ["gh workflow list", "gh pr checks"],
    fallback: [
      { level: "partial", scope: "Lint only on apps/api paths changed", when: "CI minutes" },
      { level: "defer", scope: "Document existing workflows", when: "Already green" },
      { level: "skip", scope: "mark done", when: "security.yml covers all" },
    ],
    blockedBy: [],
    debateNote: "Verify before duplicating workflows.",
  },
  {
    n: 42,
    title: "eslint react-hooks exhaustive-deps",
    category: "LINT",
    execOrder: 8,
    relevance: "medium",
    incremental: true,
    primaryScope: "eslint.config: react-hooks/exhaustive-deps error",
    verify: ["cd apps/web && npm run lint"],
    fallback: [
      { level: "partial", scope: "warn first sprint then error", when: ">50 warnings" },
      { level: "defer", scope: "Fix top 10 stale closure files", when: "Lint blocks release" },
      { level: "skip", scope: "N/A", when: "Already error" },
    ],
    blockedBy: [],
    debateNote: "UI-only; may need --full gate.",
  },
  {
    n: 43,
    title: "Pin Python deps (== / uv.lock truth)",
    category: "LINT",
    execOrder: 3,
    relevance: "medium",
    incremental: true,
    primaryScope: "requirements.txt from uv export --frozen; doc use uv sync",
    verify: ["cd apps/api && uv sync --frozen"],
    fallback: [
      { level: "partial", scope: "Pin prod deps only in requirements.txt", when: "Dev group floats" },
      { level: "defer", scope: "Document uv.lock as SoT; defer requirements.txt", when: "Vercel uses requirements" },
      { level: "skip", scope: "N/A", when: "uv.lock already canonical" },
    ],
    blockedBy: [],
    debateNote: "Week 1; check Vercel build path.",
  },
  {
    n: 44,
    title: "Dependabot or Renovate",
    category: "LINT",
    execOrder: 4,
    relevance: "medium",
    incremental: true,
    primaryScope: ".github/dependabot.yml for npm + pip/uv",
    verify: ["test -f .github/dependabot.yml"],
    fallback: [
      { level: "partial", scope: "npm only", when: "Python renovate complex" },
      { level: "defer", scope: "Manual monthly dep PR", when: "Noise too high" },
      { level: "skip", scope: "N/A", when: "Exists" },
    ],
    blockedBy: [43],
    debateNote: "After pin strategy clear.",
  },
  {
    n: 45,
    title: "Docstrings on all router functions",
    category: "DOC",
    execOrder: 46,
    relevance: "medium",
    incremental: true,
    primaryScope: "D103/D104 with template; one router per PR",
    verify: ["cd apps/api && uv run ruff check routers/ --select D"],
    fallback: [
      { level: "partial", scope: "Public staff API only", when: "144 endpoints too many" },
      { level: "defer", scope: "OpenAPI description from summary= only", when: "D rule too strict" },
      { level: "skip", scope: "N/A", when: "D disabled" },
    ],
    blockedBy: [39, 2],
    debateNote: "After Ruff D enabled.",
  },
  {
    n: 46,
    title: "OpenAPI quality from schemas + docstrings",
    category: "DOC",
    execOrder: 47,
    relevance: "medium",
    incremental: true,
    primaryScope: "tags, descriptions, examples on top 20 endpoints",
    verify: ["curl -s localhost:8000/openapi.json | jq .paths | head"],
    fallback: [
      { level: "partial", scope: "Export openapi.json to docs/", when: "No runtime change" },
      { level: "defer", scope: "After #2 #45", when: "Empty paths" },
      { level: "skip", scope: "N/A", when: "Good enough" },
    ],
    blockedBy: [2, 45],
    debateNote: "Feeds #6 codegen.",
  },
  {
    n: 47,
    title: "CHANGELOG.md Keep a Changelog",
    category: "DOC",
    execOrder: 48,
    relevance: "low",
    incremental: true,
    primaryScope: "Add CHANGELOG.md + link from README",
    verify: ["test -f CHANGELOG.md"],
    fallback: [
      { level: "partial", scope: "Unreleased section only", when: "No history" },
      { level: "defer", scope: "GitHub Releases only", when: "Jan owns releases" },
      { level: "skip", scope: "N/A", when: "Exists" },
    ],
    blockedBy: [],
    debateNote: "Process doc; quick.",
  },
  {
    n: 48,
    title: "ADRs for HS256, Vercel, Neon, no eager-load",
    category: "DOC",
    execOrder: 49,
    relevance: "medium",
    incremental: true,
    primaryScope: "docs/adr/0001-0004.md from template",
    verify: ["ls docs/adr/*.md"],
    fallback: [
      { level: "partial", scope: "2 ADRs this sprint", when: "Timeboxed" },
      { level: "defer", scope: "Bullets in ARCHITECTURE.md", when: "ADR ceremony heavy" },
      { level: "skip", scope: "N/A", when: "ARCHITECTURE sufficient" },
    ],
    blockedBy: [],
    debateNote: "High value for agents.",
  },
  {
    n: 49,
    title: "Standard error JSON {detail, code, field}",
    category: "STYLE",
    execOrder: 50,
    relevance: "high — API contract",
    incremental: true,
    primaryScope: "RFC7807 handler + migrate HTTPException to ProblemDetails",
    verify: ["cd apps/api && uv run pytest -q tests/test_errors.py"],
    fallback: [
      { level: "partial", scope: "New endpoints only; legacy string detail", when: "Breaking clients" },
      { level: "defer", scope: "Add code field optional on existing detail", when: "Web parses string only" },
      { level: "skip", scope: "N/A", when: "Already RFC7807" },
    ],
    blockedBy: [18],
    debateNote: "Coordinate with web api.ts error parsing.",
  },
  {
    n: 50,
    title: "make check — full local quality",
    category: "STYLE",
    execOrder: 5,
    relevance: "high DX",
    incremental: true,
    primaryScope: "Makefile target check → ruff + eslint + tsc + pytest (+ vitest when #31)",
    verify: ["make check"],
    fallback: [
      { level: "partial", scope: "make check-api and check-web split", when: "Windows no make" },
      { level: "defer", scope: "npm run quality:check in scripts/", when: "Make not cross-platform" },
      { level: "skip", scope: "Use deliverable gate only", when: "Duplicate" },
    ],
    blockedBy: [39, 40],
    debateNote: "Wrap existing gate scripts.",
  },
];

export function planByNumber(n) {
  return PLAN_ITEMS.find((p) => p.n === n);
}

export function orderedPlanItems() {
  return EXEC_ORDER.map((n) => planByNumber(n)).filter(Boolean);
}
