"""Shared HTTPException detail strings (Sonar S1192)."""

INSUFFICIENT_PERMISSIONS = "Insufficient permissions"
TICKET_NOT_FOUND = "Ticket not found"
USER_NOT_FOUND = "User not found"
BOARD_NOT_FOUND = "Board not found"
NOT_FOUND = "Not found"
COLUMN_NOT_FOUND = "Column not found"
GROUP_NOT_FOUND = "Group not found"
CHAT_NOT_FOUND = "Chat ikke fundet"
TASK_NOT_FOUND = "Opgave ikke fundet"
INVALID_FILE_PATH = "Ugyldig filsti"
MIN_ONE_GROUP_REQUIRED = "Mindst én rettighedsgruppe er påkrævet"
INVALID_GROUP = "Ugyldig gruppe"
