apiVersion: v1
kind: Service
metadata:
  name: stardesk-api
  namespace: {{ .Values.namespace }}
  labels:
    app: stardesk-api
    {{- include "stardesk.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: stardesk-api
  ports:
    - name: http
      port: 8000
      targetPort: http
