{{- if or .Values.secrets.databaseUrl .Values.secrets.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: stardesk-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "stardesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.cronSecret }}
  CRON_SECRET: {{ .Values.secrets.cronSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.webhookSecret }}
  WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.resendApiKey }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
  {{- end }}
{{- end }}
