apiVersion: apps/v1
kind: Deployment
metadata:
  name: stardesk-web
  namespace: {{ .Values.namespace }}
  labels:
    app: stardesk-web
    {{- include "stardesk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      app: stardesk-web
  template:
    metadata:
      labels:
        app: stardesk-web
    spec:
      automountServiceAccountToken: false
      containers:
        - name: web
          image: "{{ .Values.images.web.repository }}:{{ .Values.images.web.tag }}"
          imagePullPolicy: {{ .Values.images.web.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: stardesk-config
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
