apiVersion: v1
kind: Service
metadata:
  name: stardesk-api
  namespace: stardesk
  labels:
    app: stardesk-api
    app.kubernetes.io/name: stardesk-api
    app.kubernetes.io/part-of: stardesk
spec:
  type: ClusterIP
  selector:
    app: stardesk-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
